### ISSUE TITLE
Add support for RHEL 7.2

### ISSUE THREAD

**Issue by fhubik** [rhosqeauto/InfraRed#197]
There is a lot of problems installing IR on RHEL7.2, I noticed these major ones:

Missing prereqs in documentation:
$ yum install git python-virtualenv gcc

Missing pip
$ easy_install pip

1)
pip install -e . # BUG
Obtaining file:///home/cloud-user/InfraRed
  Running setup.py egg_info for package from file:///home/cloud-user/InfraRed
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/home/cloud-user/InfraRed/setup.py", line 9, in <module>
        install_reqs = req.parse_requirements('requirements.txt', session=False)
    TypeError: parse_requirements() got an unexpected keyword argument 'session'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
  File "<string>", line 16, in <module>
  File "/home/cloud-user/InfraRed/setup.py", line 9, in <module>
    install_reqs = req.parse_requirements('requirements.txt', session=False)
  TypeError: parse_requirements() got an unexpected keyword argument 'session'
Cleaning up...
- workaround
# line 9 in InfraRed/setup.py remove ", session=False"

2)
pip install -e . # BUG
Running setup.py install for python-keystoneclient
ImportError: No module named pytz
error in setup command: Error parsing /home/cloud-user/venv/build/python-keystoneclient/setup.cfg: ImportError: No module named pytz
- workaround
pip install pytz

3)
ir-provisioner --help # BUG # Seems to be fixed with https://github.com/rhosqeauto/InfraRed/pull/183
Traceback (most recent call last):
  File "/home/cloud-user/venv/bin/ir-provisioner", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/cloud-user/venv/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
    working_set.require(__requires__)
  File "/home/cloud-user/venv/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/cloud-user/venv/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: functools32
- workaround
pip install functools32

4)
$ pip install -e .
Downloading/unpacking funcsigs>=0.4 (from oslo.utils>=3.5.0->python-novaclient>=2.21.0,!=2.27.0,!=2.32.0->infrared==0.0.1)
  Downloading funcsigs-1.0.2.tar.gz
  Running setup.py egg_info for package funcsigs
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/home/cloud-user/venv/build/funcsigs/setup.py", line 51, in <module>
        test_suite = 'unittest2.collector',
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/cloud-user/venv/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/home/cloud-user/venv/lib/python2.7/site-packages/setuptools/dist.py", line 289, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/home/cloud-user/venv/lib/python2.7/site-packages/pkg_resources.py", line 630, in resolve
        raise VersionConflict(dist,req) # XXX put more info here
    pkg_resources.VersionConflict: (setuptools 0.9.8 (/home/cloud-user/venv/lib/python2.7/site-packages), Requirement.parse('setuptools>=17.1'))
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
  File "<string>", line 16, in <module>
  File "/home/cloud-user/venv/build/funcsigs/setup.py", line 51, in <module>
    test_suite = 'unittest2.collector',
  File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/cloud-user/venv/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__
    self.fetch_build_eggs(attrs.pop('setup_requires'))
  File "/home/cloud-user/venv/lib/python2.7/site-packages/setuptools/dist.py", line 289, in fetch_build_eggs
    parse_requirements(requires), installer=self.fetch_build_egg
  File "/home/cloud-user/venv/lib/python2.7/site-packages/pkg_resources.py", line 630, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (setuptools 0.9.8 (/home/cloud-user/venv/lib/python2.7/site-packages), Requirement.parse('setuptools>=17.1'))
- workaround
pip install --upgrade setuptools
setuptools (20.10.1)

**Comment by fhubik** [comment]
Detected another missing dependency for RHEL-7.2: openssl-devel.

**Comment by fhubik** [comment]
All reported issues solved by "pip install --upgrade pip" (pip is really outated in RHEL - 1.xx in default). Thanks @queria for this fix.
